heat_template_version: 2016-10-14
description: Autoscaling

parameters:
  public_network:
    type: string
    label: Public Network
    description: Public Network ID
    default: 96a1e024-5593-4936-bdad-869e4accac61

  dns_nameserver:
    type: comma_delimited_list
    label: DNS Name Server
    description: IP Address for access outside private network
    default: 192.168.73.252

  ssh_key_name:
    type: string
    label: Key
    description: Name of key pair. This will be used for creating new instances
    default: key
    hidden: false
    constraints:
      - custom_constraint: nova.keypair

  image_id:
    type: string
    label: Image ID
    description: Image ID (Operating System). This OS will be installed on new instances
    default: a0d4c4ee-db97-4219-91f9-5d40372ce8c1
    hidden: false
    constraints:
      - custom_constraint: glance.image

  instance_flavor:
    type: string
    label: Flavor
    description: Specs that the new instance should have
    default: 2
    hidden: false
    constraints:
      - custom_constraint: nova.flavor

  server_name:
   type: string
   label: Instance Name
   description: This name will be assigned to all newly created instances
   hidden: false
   default: webserver

  username:
    type: string
    label: Username
    description: username of the additional user
    hidden: false
    default: admin

  gecos:
    type: string
    label: users full name
    description: full name of the additional user
    hidden: false
    default: admin user

  user_key:
    type: string
    label: Public Key
    description: public key of the additional user that is injected during instance initialization
    hidden: false
    default: ssh-rsa AAAA

#______________________________________________________________________________________________________________

resources:

  private_network:
    type: OS::Neutron::Net
    properties:
      name: CloudcompGrp15-net
  private_network_subnet:
    type: OS::Neutron::Subnet
    properties:
      cidr: 192.168.0.0/24
      gateway_ip: 192.168.0.1
      allocation_pools: [{ "start": 192.168.0.50, "end": 192.168.0.200 }]
      network: { get_resource: private_network }
      name: CloudCompGrp15-subnet
      dns_nameservers: { get_param: dns_nameserver }
      enable_dhcp: true


  cloudComp_router:
    type: OS::Neutron::Router
    properties:
      name: CloudCompGrp15-router
      external_gateway_info:
        network: { get_param: public_network }

  
  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: cloudComp_router }
      subnet: { get_resource: private_network_subnet }

  
  webserver_SG:
    type: OS::Neutron::SecurityGroup
    properties:
      description: demo specific security group
      name: webserver_SG
      rules:
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - protocol: tcp
          port_range_min: 80
          port_range_max: 80


  lb:
    type: OS::Neutron::LBaaS::LoadBalancer
    properties:
      vip_subnet: { get_resource: private_network_subnet }


  lb_listener:
    type: OS::Neutron::LBaaS::Listener
    properties:
      loadbalancer: { get_resource: lb }
      protocol: HTTP
      protocol_port: 80

  
  lb_pool:
    type: OS::Neutron::LBaaS::Pool
    properties:
      listener: { get_resource: lb_listener }
      lb_algorithm: ROUND_ROBIN
      protocol: HTTP
      session_persistence:
        type: SOURCE_IP


  lb_monitor:
    type: OS::Neutron::LBaaS::HealthMonitor
    properties:
      pool: { get_resource: lb_pool }
      type: TCP
      delay: 5
      max_retries: 5
      timeout: 5


  cloud_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        users:
        - default
        - name: { get_param: username }
          gecos: { get_param: gecos }
          groups: sudo
          lock-passwd: false
          plain-text-passwd: demo
          shell: /bin/bash
          sudo: ALL=(ALL) NOPASSWD:ALL
          ssh-authorized-keys:
          - { get_param: user_key }
        package_update: true
        package_upgrade: true
        packages:
        - apache2
        write_files:
        - path: /tmp/index.html
          content: |
                <!DOCTYPE html>
                <html>
                  <body>
                    <h1>It works!</h1>
                    <h2>Hostname: hostname</h2>
                  </body>
                </html>
        runcmd:
        - sed -i "1s/$/ $(hostname)/" /etc/hosts
        - sed -i "s/hostname/$(hostname)/" /tmp/index.html
        - cp /tmp/index.html /var/www/html/index.html
        - apt-get install stress
        - stress --cpu 8
  

  demo_webserver2:
    type: OS::Nova::Server
    properties:
      name: demo_webserver2
      image: { get_param: image_id }
      flavor: { get_param: instance_flavor }
      key_name: { get_param: ssh_key_name }
      networks:
      - network: { get_resource: private_network }
      security_groups:
        - { get_resource: webserver_SG }
      user_data_format: RAW
      user_data: { get_resource: cloud_config }


  member2:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      pool: { get_resource: lb_pool }
      address: { get_attr: [demo_webserver2, first_address] }
      protocol_port: 80
      subnet: { get_resource: private_network_subnet }
  

  autoscale_group:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 2
      max_size: 4
      resource:
       type: https://raw.githubusercontent.com/RoddyGlitchh/openstack_autoscale/master/member.yaml
       properties:
        flavor: {get_param: instance_flavor}
        image: {get_param: image_id}
        server_SG: {get_resource: webserver_SG}
        key_name: {get_param: ssh_key_name}
        network: {get_resource: private_network}
        subnet: {get_resource: private_network_subnet}
        pool_id: {get_resource: lb_pool}
        metadata: { "metering.server_group": { get_param: "OS::stack_id" } }
        user_data: { get_resource: cloud_config }


  scaleout_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: autoscale_group }
      cooldown: 60
      scaling_adjustment: 1


  scalein_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: { get_resource: autoscale_group }
      cooldown: 60
      scaling_adjustment: -1


  cpu_alarm_high:
    type: OS::Aodh::GnocchiAggregationByResourcesAlarm
    properties:
      description: Scale out if CPU > 80% for 1 minute
      metric: cpu_util
      aggregation_method: mean
      granularity: 60
      evaluation_periods: 1
      threshold: 80
      resource_type: instance
      comparison_operator: gt
      alarm_actions:
        - str_replace:
            template: trust+url
            params:
              url: {get_attr: [scaleout_policy, signal_url]}
      query:
        list_join:
          - ''
          - - {'=': {server_group: {get_param: "OS::stack_id"}}}


  cpu_alarm_low:
    type: OS::Aodh::GnocchiAggregationByResourcesAlarm
    properties:
      description: Scale down if CPU < 10% for 1 minute
      metric: cpu_util
      aggregation_method: mean
      granularity: 60
      evaluation_periods: 1
      threshold: 10
      resource_type: instance
      comparison_operator: lt
      alarm_actions:
        - str_replace:
            template: trust+url
            params:
              url: {get_attr: [scalein_policy, signal_url]}
      query:
        list_join:
          - ''
          - - {'=': {server_group: {get_param: "OS::stack_id"}}}

#______________________________________________________________________________________________________________

outputs:

  pool_ip_address:
    value: { get_attr: [lb, vip_address] }
    description: The IP address of the load balancing pool
